-- 创建缺失的数据库表
-- 执行命令: docker exec agx-postgres psql -U agx -d agx -f /root/agx-dev/agx-backend/migrations/create-missing-tables.sql

-- 1. 敏感词表
CREATE TABLE IF NOT EXISTS agx_sensitive_words (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    word VARCHAR(100) UNIQUE NOT NULL,
    level SMALLINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE agx_sensitive_words IS '敏感词表';
COMMENT ON COLUMN agx_sensitive_words.level IS '级别: 1-警告, 2-禁止';
COMMENT ON COLUMN agx_sensitive_words.status IS '状态: 0-禁用, 1-启用';

-- 2. 审核日志表
CREATE TABLE IF NOT EXISTS agx_review_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    review_type VARCHAR(20) NOT NULL,
    reviewer_id BIGINT NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,
    reason VARCHAR(500),
    remark VARCHAR(500),
    extra_data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE agx_review_log IS '审核日志表';
COMMENT ON COLUMN agx_review_log.review_type IS '审核类型: post-帖子审核, comment-评论审核, report-举报处理';
COMMENT ON COLUMN agx_review_log.action IS '审核动作: approve-通过, reject-拒绝, delete-删除, modify-修改, ignore-忽略';

CREATE INDEX idx_review_type ON agx_review_log(review_type);
CREATE INDEX idx_reviewer_id ON agx_review_log(reviewer_id);
CREATE INDEX idx_target_id ON agx_review_log(target_id);
CREATE INDEX idx_action ON agx_review_log(action);
CREATE INDEX idx_created_at ON agx_review_log(created_at);

-- 3. 举报表
CREATE TABLE IF NOT EXISTS agx_report (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reporter_id BIGINT NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_id BIGINT NOT NULL,
    reason VARCHAR(50) NOT NULL,
    description VARCHAR(500),
    status SMALLINT DEFAULT 0,
    handler_id BIGINT,
    action VARCHAR(20),
    measures TEXT,
    remark VARCHAR(500),
    handled_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE agx_report IS '举报表';
COMMENT ON COLUMN agx_report.target_type IS '举报对象类型: post-帖子, comment-评论, user-用户';
COMMENT ON COLUMN agx_report.reason IS '举报原因: spam-垃圾信息, abuse-辱骂攻击, porn-色情内容, illegal-违法违规, other-其他';
COMMENT ON COLUMN agx_report.status IS '处理状态: 0-待处理, 1-已处理, -1-已忽略';
COMMENT ON COLUMN agx_report.action IS '处理动作: accept-接受, ignore-忽略';

CREATE INDEX idx_reporter_id ON agx_report(reporter_id);
CREATE INDEX idx_target_type ON agx_report(target_type);
CREATE INDEX idx_target_id ON agx_report(target_id);
CREATE INDEX idx_report_status ON agx_report(status);

-- 4. 黄金结算表
CREATE TABLE IF NOT EXISTS agx_gold_settlement (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    order_type SMALLINT NOT NULL,
    quantity VARCHAR(50) NOT NULL,
    open_price VARCHAR(50) NOT NULL,
    close_price VARCHAR(50) NOT NULL,
    profit_loss VARCHAR(50) NOT NULL,
    settled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE agx_gold_settlement IS '黄金结算记录';

CREATE INDEX idx_gold_settlement_user_id ON agx_gold_settlement(user_id);
CREATE INDEX idx_gold_settlement_symbol ON agx_gold_settlement(symbol);

-- 5. 持仓配置表
CREATE TABLE IF NOT EXISTS agx_holding_config (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    symbol VARCHAR(20) UNIQUE NOT NULL,
    min_hold VARCHAR(50) DEFAULT '0.01',
    max_hold VARCHAR(50) DEFAULT '100',
    leverage SMALLINT DEFAULT 1,
    status SMALLINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE agx_holding_config IS '持仓配置表';

-- 6. 帖子审核表
CREATE TABLE IF NOT EXISTS agx_post_review (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL,
    reviewer_id BIGINT,
    status SMALLINT DEFAULT 0,
    reason VARCHAR(500),
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE agx_post_review IS '帖子审核表';
COMMENT ON COLUMN agx_post_review.status IS '审核状态: 0-待审核, 1-通过, 2-拒绝';

-- 7. 私信表
CREATE TABLE IF NOT EXISTS agx_private_message (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    is_read SMALLINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE agx_private_message IS '私信表';
COMMENT ON COLUMN agx_private_message.is_read IS '是否已读: 0-未读, 1-已读';

CREATE INDEX idx_private_message_conversation ON agx_private_message(conversation_id);
CREATE INDEX idx_private_message_sender ON agx_private_message(sender_id);
CREATE INDEX idx_private_message_receiver ON agx_private_message(receiver_id);

-- 8. 日快照表
CREATE TABLE IF NOT EXISTS agx_daily_snapshot (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    snapshot_date DATE NOT NULL UNIQUE,
    total_users INT DEFAULT 0,
    new_users INT DEFAULT 0,
    active_users INT DEFAULT 0,
    total_orders INT DEFAULT 0,
    total_trade_volume VARCHAR(50) DEFAULT '0',
    total_recharge VARCHAR(50) DEFAULT '0',
    total_withdraw VARCHAR(50) DEFAULT '0',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE agx_daily_snapshot IS '每日数据快照表';

CREATE INDEX idx_daily_snapshot_date ON agx_daily_snapshot(snapshot_date);

-- 9. 风控预警表（在blacklist表中一起定义）
CREATE TABLE IF NOT EXISTS agx_risk_alert (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    alert_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) DEFAULT 'medium',
    description TEXT,
    status VARCHAR(20) DEFAULT 'pending',
    handled_by BIGINT,
    handled_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE agx_risk_alert IS '风控预警表';
COMMENT ON COLUMN agx_risk_alert.alert_type IS '预警类型: login_abnormal-登录异常, trade_risk-交易风险, withdraw_risk-提现风险';
COMMENT ON COLUMN agx_risk_alert.severity IS '严重程度: low-低, medium-中, high-高, critical-严重';
COMMENT ON COLUMN agx_risk_alert.status IS '状态: pending-待处理, processing-处理中, resolved-已解决, ignored-已忽略';

CREATE INDEX idx_risk_alert_user_id ON agx_risk_alert(user_id);
CREATE INDEX idx_risk_alert_status ON agx_risk_alert(status);
CREATE INDEX idx_risk_alert_created ON agx_risk_alert(created_at);
